repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: ['--unsafe']
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.1
    hooks:
      - id: ruff
        args: [ --fix, --unsafe-fixes, --ignore, 'E722' ]
        exclude: ^src/backend_v2/protos/.*$
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        exclude: ^src/backend_v2/protos/.*$
  - repo: https://github.com/asottile/reorder-python-imports
    rev: v3.13.0
    hooks:
      - id: reorder-python-imports
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
