"""Add taxi_zone_lookup table

Revision ID: 2069a96d010c
Revises: 7fbaaadb4d51
Create Date: 2025-07-08 21:58:16.218026

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "2069a96d010c"
down_revision: Union[str, Sequence[str], None] = "7fbaaadb4d51"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "taxi_zone_lookup",
        sa.Column("location_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("borough", sa.String(), nullable=True),
        sa.Column("zone", sa.String(), nullable=True),
        sa.Column("service_zone", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("location_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("taxi_zone_lookup")
    # ### end Alembic commands ###
