"""add nyc_trip table

Revision ID: f6aaf36dd238
Revises: 2069a96d010c
Create Date: 2025-07-11 02:33:27.795832

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "f6aaf36dd238"
down_revision: Union[str, Sequence[str], None] = "2069a96d010c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nyc_trip",
        sa.Column("vendor", sa.String(), nullable=False),
        sa.Column("pickup_time", sa.DateTime(), nullable=False),
        sa.Column("dropoff_time", sa.DateTime(), nullable=True),
        sa.Column("passenger_count", sa.Integer(), nullable=False),
        sa.Column("trip_distance", sa.Float(), nullable=False),
        sa.Column("pu_location_region", sa.String(), nullable=False),
        sa.Column("pu_location_zone", sa.String(), nullable=False),
        sa.Column("do_location_regin", sa.String(), nullable=False),
        sa.Column("do_location_zone", sa.String(), nullable=False),
        sa.Column("payment_type", sa.String(), nullable=False),
        sa.Column("fare_amount", sa.Float(), nullable=True),
        sa.Column("extra", sa.Float(), nullable=True),
        sa.Column("mta_tax", sa.Float(), nullable=True),
        sa.Column("tip_amount", sa.Float(), nullable=True),
        sa.Column("tolls_amount", sa.Float(), nullable=True),
        sa.Column("improvement_surcharge", sa.Float(), nullable=True),
        sa.Column("total_amount", sa.Float(), nullable=True),
        sa.Column("congestion_surcharge", sa.Float(), nullable=True),
        sa.Column("airport_fee", sa.Float(), nullable=True),
    )
    op.create_index(
        "ix_nyc_trip_time", "nyc_trip", ["pickup_time", "dropoff_time"], unique=False
    )
    op.execute("SELECT create_hypertable('nyc_trip', 'pickup_time')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_nyc_trip_time", table_name="nyc_trip")
    op.drop_table("nyc_trip")
    # ### end Alembic commands ###
