// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// source: transform.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InputFileRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InputFile      string                 `protobuf:"bytes,1,opt,name=input_file,json=inputFile,proto3" json:"input_file,omitempty"`
	RemoteFilePath string                 `protobuf:"bytes,2,opt,name=remote_file_path,json=remoteFilePath,proto3" json:"remote_file_path,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InputFileRequest) Reset() {
	*x = InputFileRequest{}
	mi := &file_transform_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputFileRequest) ProtoMessage() {}

func (x *InputFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transform_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputFileRequest.ProtoReflect.Descriptor instead.
func (*InputFileRequest) Descriptor() ([]byte, []int) {
	return file_transform_proto_rawDescGZIP(), []int{0}
}

func (x *InputFileRequest) GetInputFile() string {
	if x != nil {
		return x.InputFile
	}
	return ""
}

func (x *InputFileRequest) GetRemoteFilePath() string {
	if x != nil {
		return x.RemoteFilePath
	}
	return ""
}

type ProcessFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalRows     int64                  `protobuf:"varint,1,opt,name=total_rows,json=totalRows,proto3" json:"total_rows,omitempty"`
	DroppedRows   int64                  `protobuf:"varint,2,opt,name=dropped_rows,json=droppedRows,proto3" json:"dropped_rows,omitempty"`
	ProcessedRows int64                  `protobuf:"varint,3,opt,name=processed_rows,json=processedRows,proto3" json:"processed_rows,omitempty"`
	InsertedRows  int64                  `protobuf:"varint,4,opt,name=inserted_rows,json=insertedRows,proto3" json:"inserted_rows,omitempty"`
	MaxTime       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=max_time,json=maxTime,proto3" json:"max_time,omitempty"`
	MinTime       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=min_time,json=minTime,proto3" json:"min_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessFileResponse) Reset() {
	*x = ProcessFileResponse{}
	mi := &file_transform_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessFileResponse) ProtoMessage() {}

func (x *ProcessFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transform_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessFileResponse.ProtoReflect.Descriptor instead.
func (*ProcessFileResponse) Descriptor() ([]byte, []int) {
	return file_transform_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessFileResponse) GetTotalRows() int64 {
	if x != nil {
		return x.TotalRows
	}
	return 0
}

func (x *ProcessFileResponse) GetDroppedRows() int64 {
	if x != nil {
		return x.DroppedRows
	}
	return 0
}

func (x *ProcessFileResponse) GetProcessedRows() int64 {
	if x != nil {
		return x.ProcessedRows
	}
	return 0
}

func (x *ProcessFileResponse) GetInsertedRows() int64 {
	if x != nil {
		return x.InsertedRows
	}
	return 0
}

func (x *ProcessFileResponse) GetMaxTime() *timestamppb.Timestamp {
	if x != nil {
		return x.MaxTime
	}
	return nil
}

func (x *ProcessFileResponse) GetMinTime() *timestamppb.Timestamp {
	if x != nil {
		return x.MinTime
	}
	return nil
}

// For Testing Load Map
type InputFileTestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocationId    int64                  `protobuf:"varint,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputFileTestRequest) Reset() {
	*x = InputFileTestRequest{}
	mi := &file_transform_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputFileTestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputFileTestRequest) ProtoMessage() {}

func (x *InputFileTestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transform_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputFileTestRequest.ProtoReflect.Descriptor instead.
func (*InputFileTestRequest) Descriptor() ([]byte, []int) {
	return file_transform_proto_rawDescGZIP(), []int{2}
}

func (x *InputFileTestRequest) GetLocationId() int64 {
	if x != nil {
		return x.LocationId
	}
	return 0
}

type ProcessFileTestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Borough       string                 `protobuf:"bytes,1,opt,name=borough,proto3" json:"borough,omitempty"`
	Zone          string                 `protobuf:"bytes,2,opt,name=zone,proto3" json:"zone,omitempty"`
	ServiceZone   string                 `protobuf:"bytes,3,opt,name=service_zone,json=serviceZone,proto3" json:"service_zone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessFileTestResponse) Reset() {
	*x = ProcessFileTestResponse{}
	mi := &file_transform_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessFileTestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessFileTestResponse) ProtoMessage() {}

func (x *ProcessFileTestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transform_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessFileTestResponse.ProtoReflect.Descriptor instead.
func (*ProcessFileTestResponse) Descriptor() ([]byte, []int) {
	return file_transform_proto_rawDescGZIP(), []int{3}
}

func (x *ProcessFileTestResponse) GetBorough() string {
	if x != nil {
		return x.Borough
	}
	return ""
}

func (x *ProcessFileTestResponse) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *ProcessFileTestResponse) GetServiceZone() string {
	if x != nil {
		return x.ServiceZone
	}
	return ""
}

var File_transform_proto protoreflect.FileDescriptor

const file_transform_proto_rawDesc = "" +
	"\n" +
	"\x0ftransform.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"[\n" +
	"\x10InputFileRequest\x12\x1d\n" +
	"\n" +
	"input_file\x18\x01 \x01(\tR\tinputFile\x12(\n" +
	"\x10remote_file_path\x18\x02 \x01(\tR\x0eremoteFilePath\"\x91\x02\n" +
	"\x13ProcessFileResponse\x12\x1d\n" +
	"\n" +
	"total_rows\x18\x01 \x01(\x03R\ttotalRows\x12!\n" +
	"\fdropped_rows\x18\x02 \x01(\x03R\vdroppedRows\x12%\n" +
	"\x0eprocessed_rows\x18\x03 \x01(\x03R\rprocessedRows\x12#\n" +
	"\rinserted_rows\x18\x04 \x01(\x03R\finsertedRows\x125\n" +
	"\bmax_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\amaxTime\x125\n" +
	"\bmin_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aminTime\"7\n" +
	"\x14InputFileTestRequest\x12\x1f\n" +
	"\vlocation_id\x18\x01 \x01(\x03R\n" +
	"locationId\"j\n" +
	"\x17ProcessFileTestResponse\x12\x18\n" +
	"\aborough\x18\x01 \x01(\tR\aborough\x12\x12\n" +
	"\x04zone\x18\x02 \x01(\tR\x04zone\x12!\n" +
	"\fservice_zone\x18\x03 \x01(\tR\vserviceZone2\x94\x01\n" +
	"\x10TransformService\x12;\n" +
	"\x0eProcessNYCTrip\x12\x11.InputFileRequest\x1a\x14.ProcessFileResponse\"\x00\x12C\n" +
	"\x0eProcessTesting\x12\x15.InputFileTestRequest\x1a\x18.ProcessFileTestResponse\"\x00B\x19Z\x17processor/protos;protosb\x06proto3"

var (
	file_transform_proto_rawDescOnce sync.Once
	file_transform_proto_rawDescData []byte
)

func file_transform_proto_rawDescGZIP() []byte {
	file_transform_proto_rawDescOnce.Do(func() {
		file_transform_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transform_proto_rawDesc), len(file_transform_proto_rawDesc)))
	})
	return file_transform_proto_rawDescData
}

var file_transform_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_transform_proto_goTypes = []any{
	(*InputFileRequest)(nil),        // 0: InputFileRequest
	(*ProcessFileResponse)(nil),     // 1: ProcessFileResponse
	(*InputFileTestRequest)(nil),    // 2: InputFileTestRequest
	(*ProcessFileTestResponse)(nil), // 3: ProcessFileTestResponse
	(*timestamppb.Timestamp)(nil),   // 4: google.protobuf.Timestamp
}
var file_transform_proto_depIdxs = []int32{
	4, // 0: ProcessFileResponse.max_time:type_name -> google.protobuf.Timestamp
	4, // 1: ProcessFileResponse.min_time:type_name -> google.protobuf.Timestamp
	0, // 2: TransformService.ProcessNYCTrip:input_type -> InputFileRequest
	2, // 3: TransformService.ProcessTesting:input_type -> InputFileTestRequest
	1, // 4: TransformService.ProcessNYCTrip:output_type -> ProcessFileResponse
	3, // 5: TransformService.ProcessTesting:output_type -> ProcessFileTestResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_transform_proto_init() }
func file_transform_proto_init() {
	if File_transform_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transform_proto_rawDesc), len(file_transform_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transform_proto_goTypes,
		DependencyIndexes: file_transform_proto_depIdxs,
		MessageInfos:      file_transform_proto_msgTypes,
	}.Build()
	File_transform_proto = out.File
	file_transform_proto_goTypes = nil
	file_transform_proto_depIdxs = nil
}
